In [1]:
import numpy as np

In [2]:
l = [1, 2, 3, 4]

In [3]:
len(l)

4

In [4]:
l[2]

3

In [6]:
a = np.array(l)

In [7]:
a

array([1, 2, 3, 4])

In [8]:
print(a) # lacks commas as would be seen in a list

[1 2 3 4]


In [9]:
l

[1, 2, 3, 4]

In [10]:
list(a)

[np.int64(1), np.int64(2), np.int64(3), np.int64(4)]

In [13]:
a

array([1, 2, 3, 4])

In [11]:
# numpy arrays provide supersets of operations not present in a normal list

for x in a:
    print(x + 1)

2
3
4
5


In [12]:
l + 1

TypeError: can only concatenate list (not "int") to list

In [15]:
a + 1  # no need for a for loop, it mirrors the mathematical notation of matrices

array([2, 3, 4, 5])

In [18]:
l = range(1000)

sq1 = [val**2 for val in l]

In [19]:
sq1

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801,
 10000,
 10201,
 10404,
 10609,
 10816,
 11025,
 11236,
 11449,
 11664,
 11881,
 12100,
 12321,
 12544,
 12769,
 12996,
 13225,
 13456,
 13689,
 13924,
 14161,
 14400,
 14641,
 14884,
 15129,
 15376,
 15625,
 15876,
 16129,
 16384,
 16641,
 16900,
 17161,
 17424,
 17689,
 17956,
 18225,
 18496,
 18769,
 19044,
 19321,
 19600,
 19881,
 20164,
 2

In [21]:
a = np.arange(1000)
sq2 = a ** 2

In [22]:
sq2

array([     0,      1,      4,      9,     16,     25,     36,     49,
           64,     81,    100,    121,    144,    169,    196,    225,
          256,    289,    324,    361,    400,    441,    484,    529,
          576,    625,    676,    729,    784,    841,    900,    961,
         1024,   1089,   1156,   1225,   1296,   1369,   1444,   1521,
         1600,   1681,   1764,   1849,   1936,   2025,   2116,   2209,
         2304,   2401,   2500,   2601,   2704,   2809,   2916,   3025,
         3136,   3249,   3364,   3481,   3600,   3721,   3844,   3969,
         4096,   4225,   4356,   4489,   4624,   4761,   4900,   5041,
         5184,   5329,   5476,   5625,   5776,   5929,   6084,   6241,
         6400,   6561,   6724,   6889,   7056,   7225,   7396,   7569,
         7744,   7921,   8100,   8281,   8464,   8649,   8836,   9025,
         9216,   9409,   9604,   9801,  10000,  10201,  10404,  10609,
        10816,  11025,  11236,  11449,  11664,  11881,  12100,  12321,
      

In [23]:
# compare time

%timeit sq1 = [val**2 for val in l]

49.4 μs ± 2.63 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [25]:
%timeit sq2 = a ** 2 # faster because numpy requires integers in the array, gaining time and constraining checks that native python would do

869 ns ± 15.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [26]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.

In [27]:
np.ar*?

np.arange
np.arccos
np.arccosh
np.arcsin
np.arcsinh
np.arctan
np.arctan2
np.arctanh
np.argmax
np.argmin
np.argpartition
np.argsort
np.argwhere
np.around
np.array
np.array2string
np.array_equal
np.array_equiv
np.array_repr
np.array_split
np.array_str

In [30]:
a = np.array([2, 3, 4])

In [31]:
a

array([2, 3, 4])

In [33]:
m = np.array([[1, 2, 3], 
          [3, 4, 5], 
          [6, 7, 8]])

In [34]:
a.shape

(3,)

In [35]:
m.shape

(3, 3)

In [36]:
np.linspace(0, 1, 6)  #start, end, cut values to generate 6 numbers that are covering the whole interval from start to finish

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [39]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
np.ones(10) * 2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [43]:
np.eye(5) # 5 x 5 array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
# random numbers
np.random.rand(2, 5)


array([[0.70343708, 0.7424647 , 0.06766389, 0.03020688, 0.68332499],
       [0.42307722, 0.58864045, 0.47627998, 0.23441519, 0.30601813]])

In [45]:
np.random.randn(3, 5)

array([[ 1.63867549e+00,  2.20684506e+00,  1.46157394e+00,
         1.90859229e-01, -6.48720981e-01],
       [ 1.03852996e+00,  7.25859884e-01, -6.83722974e-01,
         1.28716975e-03,  1.25035033e+00],
       [-4.24734171e-01,  7.14925163e-01, -7.02077152e-02,
         7.36464445e-01,  1.62303216e+00]])

In [46]:
np.random.randn(4, 5) * 2 + 1

array([[-0.28754942, -1.94996996,  2.10036274,  5.35458006, -1.84924613],
       [-1.94776382,  4.66177942,  4.79345983,  4.19804316,  3.98909837],
       [ 1.73657226, -1.27935248,  0.43998794, -1.11550962,  1.76251828],
       [ 4.77034618,  0.2873278 ,  2.63844236,  0.49729317, -3.13858344]])

In [47]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a.dtype

dtype('int64')

In [50]:
b = np.linspace(0, 1, 10)
b

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [51]:
b.dtype

dtype('float64')

In [52]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a[1]

np.int64(1)

In [55]:
a = np.arange(3)
a

array([0, 1, 2])

In [56]:
mask = np.array([False, True, False])

## Using the boolean mask to call the array. Why?

In [57]:
a[mask]

array([1])

In [58]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [61]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [62]:
a[a > 5]

array([6, 7, 8, 9])

In [ ]:
np.random.randn(3, 5) * 2 + 1 # order of operation defined by order inserted. Multiplying by 2 (variance) has precendence to adding/shifting by 1 (std)

## Reshaping

In [63]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
a.shape # 1 dimension

(10,)

In [66]:
a.reshape((2, 5)) # a 2x5 matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [67]:
a.reshape((3, 5))

ValueError: cannot reshape array of size 10 into shape (3,5)

In [70]:
a.reshape((1, 10)).T  # column vector

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [69]:
a.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
np.array([1, 2, 3]) + 1

array([2, 3, 4])

In [76]:
np.array([1, 2, 3]) + np.array([4, 5, 6])

array([5, 7, 9])

In [77]:
np.array([1, 2, 3]) + np.array([4, 5])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [78]:
a = np.arange(5)
b = np.arange(10).reshape((2, 5))

In [79]:
a

array([0, 1, 2, 3, 4])

In [80]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [81]:
a.shape

(5,)

In [82]:
b.shape

(2, 5)

In [83]:
a + b

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [86]:
a1 = a.reshape((1, 5))
a1

array([[0, 1, 2, 3, 4]])

In [87]:
a1.shape

(1, 5)

In [90]:
a2 = np.zeros((2, 5)) 

In [91]:
a2[0] = a1
a2[1] = a1

In [92]:
a2

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [93]:
a2.shape

(2, 5)

In [94]:
a2 + b 

array([[ 0.,  2.,  4.,  6.,  8.],
       [ 5.,  7.,  9., 11., 13.]])

In [95]:
a

array([0, 1, 2, 3, 4])

In [96]:
a.shape

(5,)

In [97]:
a + b

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [98]:
a = np.arange(3)

In [99]:
a.shape

(3,)

In [100]:
a + b

ValueError: operands could not be broadcast together with shapes (3,) (2,5) 

In [101]:
a1 = a.reshape((1, 3))

In [102]:
a1

array([[0, 1, 2]])

In [103]:
a2 = np.zeros((2, 3))
a2[0] = a1
a2[1] = a1
a2

array([[0., 1., 2.],
       [0., 1., 2.]])

In [104]:
a2 + b

ValueError: operands could not be broadcast together with shapes (2,3) (2,5) 

In [105]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [106]:
a.shape

(3,)

In [107]:
b.shape

(2, 5)

# ORF
Open Reading Frame


1. Find ATG
2. Iterate triplets
3. Take a codon, convert to amino acid
4. Loop until the stop codon

In [130]:
seq = "AAAAAATGCCTATGGATAATGTGA" # example

In [128]:
codontab = {
    'TCA': 'S',    # Serina
    'TCC': 'S',    # Serina
    'TCG': 'S',    # Serina
    'TCT': 'S',    # Serina
    'TTC': 'F',    # Fenilalanina
    'TTT': 'F',    # Fenilalanina
    'TTA': 'L',    # Leucina
    'TTG': 'L',    # Leucina
    'TAC': 'Y',    # Tirosina
    'TAT': 'Y',    # Tirosina
    'TAA': '*',    # Stop
    'TAG': '*',    # Stop
    'TGC': 'C',    # Cisteina
    'TGT': 'C',    # Cisteina
    'TGA': '*',    # Stop
    'TGG': 'W',    # Triptofano
    'CTA': 'L',    # Leucina
    'CTC': 'L',    # Leucina
    'CTG': 'L',    # Leucina
    'CTT': 'L',    # Leucina
    'CCA': 'P',    # Prolina
    'CCC': 'P',    # Prolina
    'CCG': 'P',    # Prolina
    'CCT': 'P',    # Prolina
    'CAC': 'H',    # Histidina
    'CAT': 'H',    # Histidina
    'CAA': 'Q',    # Glutamina
    'CAG': 'Q',    # Glutamina
    'CGA': 'R',    # Arginina
    'CGC': 'R',    # Arginina
    'CGG': 'R',    # Arginina
    'CGT': 'R',    # Arginina
    'ATA': 'I',    # Isoleucina
    'ATC': 'I',    # Isoleucina
    'ATT': 'I',    # Isoleucina
    'ATG': 'M',    # Methionina
    'ACA': 'T',    # Treonina
    'ACC': 'T',    # Treonina
    'ACG': 'T',    # Treonina
    'ACT': 'T',    # Treonina
    'AAC': 'N',    # Asparagina
    'AAT': 'N',    # Asparagina
    'AAA': 'K',    # Lisina
    'AAG': 'K',    # Lisina
    'AGC': 'S',    # Serina
    'AGT': 'S',    # Serina
    'AGA': 'R',    # Arginina
    'AGG': 'R',    # Arginina
    'GTA': 'V',    # Valina
    'GTC': 'V',    # Valina
    'GTG': 'V',    # Valina
    'GTT': 'V',    # Valina
    'GCA': 'A',    # Alanina
    'GCC': 'A',    # Alanina
    'GCG': 'A',    # Alanina
    'GCT': 'A',    # Alanina
    'GAC': 'D',    # Acido Aspartico
    'GAT': 'D',    # Acido Aspartico
    'GAA': 'E',    # Acido Glutamico
    'GAG': 'E',    # Acido Glutamico
    'GGA': 'G',    # Glicina
    'GGC': 'G',    # Glicina
    'GGG': 'G',    # Glicina
    'GGT': 'G'     # Glicina
}

In [110]:
def find_atg(seq):
    ...

In [111]:
def find_stop(seq):
    ...

In [112]:
def convert_codons(seq):
    ...

In [113]:
def predict_orf(seq):
    ...

In [114]:
seq.find("ATG")

5

In [115]:
seq

'AAAAAATGCCTATGGA'

In [116]:
def find_atg(seq):
    pos = seq.find("ATG")
    # account for potential errors
    assert pos >= 0, "there is no ATG in the sequence"
    return pos

In [117]:
find_atg(seq)

5

In [125]:
def find_stop(seq):
    for pos in range(0, len(seq), 3):
        triplet = seq[pos:pos+3]
        if codontab[triplet] == "*":
            return pos

In [131]:
find_stop(seq)

21

In [133]:
seq[21:]

'TGA'